/** English defines the keys and message kinds for every locale. */
export const en = {
  "editor.addEntry": "Add an entry",
  "editor.newEntry": "NEW ENTRY",
  "editor.addToEveria": "Add to Everia",
  "editor.addMethod": "Add entry method",
  "editor.onlineSearch": "Online search",
  "editor.manualEntry": "Manual entry",
  "editor.importedNotice":
    "{provider} metadata loaded. Review it before saving your local Everia entry.",
  "editor.localCover": "Local cover image",
  "editor.title": "Title",
  "editor.category": "Category",
  "editor.type": "Type",
  "editor.authorCreator": "Author / creator",
  "editor.optional": "Optional",
  "editor.releaseExample": "2024 or 2024-05-12",
  "editor.runtimeMinutes": "Runtime (minutes)",
  "editor.rating": "Rating",
  "editor.coverUrl": "Cover image URL",
  "editor.description": "Description",
  "editor.summaryPlaceholder": "A short summary...",
  "editor.notesPlaceholder": "Thoughts, progress, reminders...",
  "editor.savingLocal": "Saving local copy…",
  "editor.saveToLibrary": "Save to library",
  "details.entryDetails": "Entry details",
  "details.backTo": "Back to {destination}",
  "details.removeFavorite": "Remove from favorites",
  "details.addFavorite": "Add to favorites",
  "details.edit": "Edit",
  "details.myRating": "My rating",
  "details.status": "Status",
  "details.platform": "Platform",
  "details.runtime": "Runtime",
  "details.minutes": "{count} min",
  "details.seasons": "Seasons",
  "details.episodes": "Episodes",
  "details.volumes": "Volumes",
  "details.chapters": "Chapters",
  "details.genre": "Genre",
  "details.yearRelease": "Year / Release",
  "details.link": "Link",
  "details.linkLabel": "Link label",
  "details.official": "Official",
  "details.summary": "Summary",
  "details.myNotes": "My notes",
  "details.noNotes": "No personal notes yet.",
  "details.savedLocally": "Saved locally",
  "details.editEntry": "EDIT ENTRY",
  "details.saveHint": "Changes are stored only when you choose Save Changes.",
  "details.replaceCover": "Replace cover",
  "details.coverCopied": "{filename} will be copied into Everia.",
  "details.remove": "Remove from Everia",
  "details.saving": "Saving…",
  "details.saveChanges": "Save Changes",
  "search.providerQuery": "Search {provider}",
  "search.online": "Online",
  "search.placeholder": "Search by title...",
  "search.searching": "Searching…",
  "search.action": "Search",
  "search.fallback": "{from} is unavailable. Searching {to} instead.",
  "search.empty": "No matching entries were found.",
  "search.desktopOnly": "Online search is available in the Everia desktop app.",
  "search.notSupported": "Online search is unavailable for this category.",
  "search.allUnavailable": "Online sources are currently unavailable.",
  "search.credentials": "Online source credentials need attention.",
  "search.timeout": "The search timed out. Please try again.",
  "search.rateLimit": "The online source is busy. Please try again later.",
  "search.detailsUnavailable":
    "Could not load this entry’s details. You can retry or choose another result.",
  "search.unavailable": "Online search is unavailable. Please try again.",
  "search.configure": "Configure sources",
  "search.retry": "Retry",
  "search.importPreview": "Import preview",
  "search.volumes": { one: "{count} volume", other: "{count} volumes" },
  "search.loadingDetails": "Loading details…",
  "search.useEntry": "Use this entry",
  "search.backToResults": "Back to results",
  "search.results": "Search results",
  "search.additionalDetails": "Additional details unavailable",
  "search.rawgAttribution": "Game data provided by",
  "errors.entrySave": "Could not save. Try a local image file.",

  "common.cancel": "Cancel",
  "common.savedFor": "Saved for {name}",
  "navigation.home": "Home",
  "navigation.favorites": "Favorites",
  "navigation.settings": "Settings",
  "navigation.everiaHome": "Everia home",
  "navigation.close": "Close navigation",
  "navigation.open": "Open navigation",
  "navigation.search": "Search your universe",
  "navigation.searchPlaceholder": "Search your universe...",
  "navigation.addItem": "Add item",
  "categories.games": "Games",
  "categories.movies": "Movies",
  "categories.tv": "TV Shows",
  "categories.novels": "Novels",
  "categories.manga": "Manga",
  "categories.anime": "Anime",
  "categories.gamesDescription": "Worlds you can explore",
  "categories.moviesDescription": "Stories for the big screen",
  "categories.tvDescription": "One episode at a time",
  "categories.novelsDescription": "Novel · Light Novel · Web Novel",
  "categories.mangaDescription": "Manga · Manhwa · Manhua",
  "categories.animeDescription": "Worlds in motion",
  "subtypes.novel": "Novel",
  "subtypes.lightNovel": "Light Novel",
  "subtypes.webNovel": "Web Novel",
  "subtypes.manga": "Manga",
  "subtypes.manhwa": "Manhwa",
  "subtypes.manhua": "Manhua",
  "statuses.wantToPlay": "Want to Play",
  "statuses.playing": "Playing",
  "statuses.played": "Played",
  "statuses.wantToWatch": "Want to Watch",
  "statuses.watching": "Watching",
  "statuses.watched": "Watched",
  "statuses.completed": "Completed",
  "statuses.wantToRead": "Want to Read",
  "statuses.reading": "Reading",
  "statuses.read": "Read",
  "statuses.onHold": "On Hold",
  "statuses.dropped": "Dropped",
  "creators.developer": "Developer",
  "creators.director": "Director",
  "creators.creator": "Creator",
  "creators.author": "Author",
  "creators.studio": "Studio",
  "contributors.cast": "Cast",
  "contributors.artist": "Artist",
  "home.tagline": "Your Personal Universe",
  "home.entryCount": { one: "{count} entry", other: "{count} entries" },
  "home.footer": "“Stories, worlds, and experiences that stay with you.”",
  "library.collection": "COLLECTION",
  "library.sortBy": "Sort by",
  "library.recentlyAdded": "Recently added",
  "library.title": "Title",
  "library.releaseDate": "Release date",
  "library.rating": "Rating",
  "library.view": "Library view",
  "library.gridView": "Grid view",
  "library.listView": "List view",
  "library.filterByStatus": "Filter by status",
  "library.all": "All",
  "library.unknownCreator": "Unknown creator",
  "library.empty": "No entries here yet",
  "library.emptyPrompt":
    "Add an entry manually or find one with online search.",
  "library.noStatusMatches": "No entries match this status.",
  "library.addItem": "Add an item",
  "favorites.subtitle": "The stories and worlds you love most.",
  "favorites.empty": "No favorites yet",
  "favorites.emptyPrompt": "Mark an entry as a favorite to find it here.",
  "settings.language": "Language",
  "errors.unavailable": "{source} is currently unavailable.",
  "errors.savedDataUnreadable":
    "Some saved data could not be loaded. It has been preserved; saving that data is disabled until repaired.",
  "errors.themeSave": "Theme could not be saved.",
  "errors.sortSave": "Sort preference could not be saved.",
  "errors.viewSave": "View preference could not be saved.",
  "errors.removeConfirm": "Remove this entry? This cannot be undone.",
  "errors.removeFailed": "Entry could not be removed.",
  "errors.changesSave":
    "Changes could not be saved. Check storage space and retry.",
  "accessibility.openEntry": "Open {title}",
  "accessibility.coverOf": "Cover of {title}",
  "accessibility.notRated": "Not rated",
  "accessibility.ratingOutOfTen": "{rating} out of 10",
  "accessibility.rateOutOfTen": "Rate {rating} out of 10",
  "accessibility.clearRating": "Clear",
} as const;

export type MessageKey = keyof typeof en;
export type PluralCategory = Intl.LDMLPluralRule;
export type PluralMessage = { other: string } & Partial<
  Record<PluralCategory, string>
>;
export type CatalogShape = {
  [K in MessageKey]: (typeof en)[K] extends string ? string : PluralMessage;
};

export const fr = {
  "editor.addEntry": "Ajouter une entrée",
  "editor.newEntry": "NOUVELLE ENTRÉE",
  "editor.addToEveria": "Ajouter à Everia",
  "editor.addMethod": "Méthode d’ajout",
  "editor.onlineSearch": "Recherche en ligne",
  "editor.manualEntry": "Saisie manuelle",
  "editor.importedNotice":
    "Métadonnées de {provider} chargées. Vérifiez-les avant d’enregistrer votre entrée locale dans Everia.",
  "editor.localCover": "Image de couverture locale",
  "editor.title": "Titre",
  "editor.category": "Catégorie",
  "editor.type": "Type",
  "editor.authorCreator": "Auteur / créateur",
  "editor.optional": "Facultatif",
  "editor.releaseExample": "2024 ou 2024-05-12",
  "editor.runtimeMinutes": "Durée (minutes)",
  "editor.rating": "Note",
  "editor.coverUrl": "URL de la couverture",
  "editor.description": "Description",
  "editor.summaryPlaceholder": "Un bref résumé...",
  "editor.notesPlaceholder": "Impressions, progression, rappels...",
  "editor.savingLocal": "Enregistrement de la copie locale…",
  "editor.saveToLibrary": "Enregistrer dans la collection",
  "details.entryDetails": "Détails de l’entrée",
  "details.backTo": "Retour à {destination}",
  "details.removeFavorite": "Retirer des favoris",
  "details.addFavorite": "Ajouter aux favoris",
  "details.edit": "Modifier",
  "details.myRating": "Ma note",
  "details.status": "Statut",
  "details.platform": "Plateforme",
  "details.runtime": "Durée",
  "details.minutes": "{count} min",
  "details.seasons": "Saisons",
  "details.episodes": "Épisodes",
  "details.volumes": "Tomes",
  "details.chapters": "Chapitres",
  "details.genre": "Genre",
  "details.yearRelease": "Année / sortie",
  "details.link": "Lien",
  "details.linkLabel": "Libellé du lien",
  "details.official": "Officiel",
  "details.summary": "Résumé",
  "details.myNotes": "Mes notes",
  "details.noNotes": "Aucune note personnelle pour le moment.",
  "details.savedLocally": "Enregistré localement",
  "details.editEntry": "MODIFIER L’ENTRÉE",
  "details.saveHint":
    "Les modifications ne sont enregistrées qu’après avoir choisi Enregistrer les modifications.",
  "details.replaceCover": "Remplacer la couverture",
  "details.coverCopied": "{filename} sera copié dans Everia.",
  "details.remove": "Supprimer d’Everia",
  "details.saving": "Enregistrement…",
  "details.saveChanges": "Enregistrer les modifications",
  "search.providerQuery": "Rechercher sur {provider}",
  "search.online": "En ligne",
  "search.placeholder": "Rechercher des titres...",
  "search.searching": "Recherche…",
  "search.action": "Rechercher",
  "search.fallback": "{from} est indisponible. Recherche sur {to} à la place.",
  "search.empty": "Aucune entrée correspondante trouvée.",
  "search.desktopOnly":
    "La recherche en ligne est disponible dans l’application de bureau.",
  "search.notSupported":
    "La recherche en ligne n’est pas disponible pour cette catégorie.",
  "search.allUnavailable":
    "Les sources en ligne sont actuellement indisponibles.",
  "search.credentials":
    "Les identifiants des sources en ligne nécessitent votre attention.",
  "search.timeout": "La recherche a expiré. Réessayez.",
  "search.rateLimit": "La source en ligne est occupée. Réessayez plus tard.",
  "search.detailsUnavailable":
    "Impossible de charger les détails de cette entrée. Réessayez ou choisissez un autre résultat.",
  "search.unavailable": "La recherche en ligne est indisponible. Réessayez.",
  "search.configure": "Configurer les sources",
  "search.retry": "Réessayer",
  "search.importPreview": "Aperçu de l’importation",
  "search.volumes": { one: "{count} tome", other: "{count} tomes" },
  "search.loadingDetails": "Chargement des détails…",
  "search.useEntry": "Utiliser cette entrée",
  "search.backToResults": "Retour aux résultats",
  "search.results": "Résultats de recherche",
  "search.additionalDetails": "Détails supplémentaires indisponibles",
  "search.rawgAttribution": "Données des jeux fournies par",
  "errors.entrySave": "Impossible d’enregistrer. Essayez une image locale.",

  "common.cancel": "Annuler",
  "common.savedFor": "Enregistré pour {name}",
  "navigation.home": "Accueil",
  "navigation.favorites": "Favoris",
  "navigation.settings": "Paramètres",
  "navigation.everiaHome": "Accueil d’Everia",
  "navigation.close": "Fermer la navigation",
  "navigation.open": "Ouvrir la navigation",
  "navigation.search": "Rechercher dans votre univers",
  "navigation.searchPlaceholder": "Rechercher dans votre univers...",
  "navigation.addItem": "Ajouter",
  "categories.games": "Jeux",
  "categories.movies": "Films",
  "categories.tv": "Séries TV",
  "categories.novels": "Romans",
  "categories.manga": "Mangas",
  "categories.anime": "Animés",
  "categories.gamesDescription": "Des mondes à explorer",
  "categories.moviesDescription": "Des histoires pour le grand écran",
  "categories.tvDescription": "Un épisode à la fois",
  "categories.novelsDescription": "Roman · Light novel · Web novel",
  "categories.mangaDescription": "Manga · Manhwa · Manhua",
  "categories.animeDescription": "Des mondes en mouvement",
  "subtypes.novel": "Roman",
  "subtypes.lightNovel": "Light novel",
  "subtypes.webNovel": "Web novel",
  "subtypes.manga": "Manga",
  "subtypes.manhwa": "Manhwa",
  "subtypes.manhua": "Manhua",
  "statuses.wantToPlay": "À jouer",
  "statuses.playing": "En cours",
  "statuses.played": "Terminé",
  "statuses.wantToWatch": "À regarder",
  "statuses.watching": "En cours",
  "statuses.watched": "Vu",
  "statuses.completed": "Terminé",
  "statuses.wantToRead": "À lire",
  "statuses.reading": "En cours",
  "statuses.read": "Lu",
  "statuses.onHold": "En pause",
  "statuses.dropped": "Abandonné",
  "creators.developer": "Développeur",
  "creators.director": "Réalisateur",
  "creators.creator": "Créateur",
  "creators.author": "Auteur",
  "creators.studio": "Studio",
  "contributors.cast": "Distribution",
  "contributors.artist": "Artiste",
  "home.tagline": "Votre univers personnel",
  "home.entryCount": { one: "{count} entrée", other: "{count} entrées" },
  "home.footer":
    "« Des histoires, des mondes et des expériences qui restent avec vous. »",
  "library.collection": "COLLECTION",
  "library.sortBy": "Trier par",
  "library.recentlyAdded": "Ajouts récents",
  "library.title": "Titre",
  "library.releaseDate": "Date de sortie",
  "library.rating": "Note",
  "library.view": "Affichage de la collection",
  "library.gridView": "Vue en grille",
  "library.listView": "Vue en liste",
  "library.filterByStatus": "Filtrer par statut",
  "library.all": "Tout",
  "library.unknownCreator": "Créateur inconnu",
  "library.empty": "Aucune entrée pour le moment",
  "library.emptyPrompt":
    "Ajoutez une entrée manuellement ou trouvez-en une avec la recherche en ligne.",
  "library.noStatusMatches": "Aucune entrée ne correspond à ce statut.",
  "library.addItem": "Ajouter une entrée",
  "favorites.subtitle": "Les histoires et les mondes que vous aimez le plus.",
  "favorites.empty": "Aucun favori pour le moment",
  "favorites.emptyPrompt":
    "Ajoutez une entrée à vos favoris pour la retrouver ici.",
  "settings.language": "Langue",
  "errors.unavailable": "{source} est actuellement indisponible.",
  "errors.savedDataUnreadable":
    "Certaines données enregistrées n’ont pas pu être chargées. Elles ont été préservées ; leur enregistrement est désactivé jusqu’à leur réparation.",
  "errors.themeSave": "Impossible d’enregistrer le thème.",
  "errors.sortSave": "Impossible d’enregistrer le tri.",
  "errors.viewSave": "Impossible d’enregistrer l’affichage.",
  "errors.removeConfirm":
    "Supprimer cette entrée ? Cette action est irréversible.",
  "errors.removeFailed": "Impossible de supprimer l’entrée.",
  "errors.changesSave":
    "Impossible d’enregistrer les modifications. Vérifiez l’espace disponible et réessayez.",
  "accessibility.openEntry": "Ouvrir {title}",
  "accessibility.coverOf": "Couverture de {title}",
  "accessibility.notRated": "Pas encore noté",
  "accessibility.ratingOutOfTen": "{rating} sur 10",
  "accessibility.rateOutOfTen": "Noter {rating} sur 10",
  "accessibility.clearRating": "Effacer",
} satisfies CatalogShape;

export const ar = {
  "editor.addEntry": "إضافة عنصر",
  "editor.newEntry": "عنصر جديد",
  "editor.addToEveria": "إضافة إلى Everia",
  "editor.addMethod": "طريقة إضافة العنصر",
  "editor.onlineSearch": "البحث عبر الإنترنت",
  "editor.manualEntry": "إدخال يدوي",
  "editor.importedNotice":
    "حُمّلت بيانات {provider}. راجعها قبل حفظ العنصر محليًا في Everia.",
  "editor.localCover": "صورة غلاف محلية",
  "editor.title": "العنوان",
  "editor.category": "الفئة",
  "editor.type": "النوع",
  "editor.authorCreator": "المؤلف / المُنشئ",
  "editor.optional": "اختياري",
  "editor.releaseExample": "2024 أو 2024-05-12",
  "editor.runtimeMinutes": "المدة (بالدقائق)",
  "editor.rating": "التقييم",
  "editor.coverUrl": "رابط صورة الغلاف",
  "editor.description": "الوصف",
  "editor.summaryPlaceholder": "ملخص قصير...",
  "editor.notesPlaceholder": "أفكار، تقدم، تذكيرات...",
  "editor.savingLocal": "جارٍ حفظ النسخة المحلية…",
  "editor.saveToLibrary": "حفظ في المجموعة",
  "details.entryDetails": "تفاصيل العنصر",
  "details.backTo": "العودة إلى {destination}",
  "details.removeFavorite": "إزالة من المفضلة",
  "details.addFavorite": "إضافة إلى المفضلة",
  "details.edit": "تعديل",
  "details.myRating": "تقييمي",
  "details.status": "الحالة",
  "details.platform": "المنصة",
  "details.runtime": "المدة",
  "details.minutes": "{count} دقيقة",
  "details.seasons": "المواسم",
  "details.episodes": "الحلقات",
  "details.volumes": "المجلدات",
  "details.chapters": "الفصول",
  "details.genre": "التصنيف",
  "details.yearRelease": "السنة / الإصدار",
  "details.link": "الرابط",
  "details.linkLabel": "تسمية الرابط",
  "details.official": "رسمي",
  "details.summary": "الملخص",
  "details.myNotes": "ملاحظاتي",
  "details.noNotes": "لا توجد ملاحظات شخصية بعد.",
  "details.savedLocally": "محفوظ محليًا",
  "details.editEntry": "تعديل العنصر",
  "details.saveHint": "لن تُحفظ التغييرات إلا عند اختيار حفظ التغييرات.",
  "details.replaceCover": "استبدال الغلاف",
  "details.coverCopied": "سيُنسخ {filename} إلى Everia.",
  "details.remove": "إزالة من Everia",
  "details.saving": "جارٍ الحفظ…",
  "details.saveChanges": "حفظ التغييرات",
  "search.providerQuery": "البحث في {provider}",
  "search.online": "عبر الإنترنت",
  "search.placeholder": "ابحث عن عناوين...",
  "search.searching": "جارٍ البحث…",
  "search.action": "بحث",
  "search.fallback": "{from} غير متاح. جارٍ البحث في {to} بدلًا منه.",
  "search.empty": "لم يُعثر على عناصر مطابقة.",
  "search.desktopOnly": "البحث عبر الإنترنت متاح في تطبيق سطح المكتب.",
  "search.notSupported": "البحث عبر الإنترنت غير متاح لهذه الفئة.",
  "search.allUnavailable": "المصادر عبر الإنترنت غير متاحة حاليًا.",
  "search.credentials": "بيانات اعتماد المصادر عبر الإنترنت تتطلب الانتباه.",
  "search.timeout": "انتهت مهلة البحث. حاول مجددًا.",
  "search.rateLimit": "المصدر عبر الإنترنت مشغول. حاول لاحقًا.",
  "search.detailsUnavailable":
    "تعذّر تحميل تفاصيل هذا العنصر. حاول مجددًا أو اختر نتيجة أخرى.",
  "search.unavailable": "البحث عبر الإنترنت غير متاح. حاول مجددًا.",
  "search.configure": "إعداد المصادر",
  "search.retry": "إعادة المحاولة",
  "search.importPreview": "معاينة الاستيراد",
  "search.volumes": {
    zero: "{count} مجلدات",
    one: "{count} مجلد",
    two: "{count} مجلدان",
    few: "{count} مجلدات",
    many: "{count} مجلدًا",
    other: "{count} مجلد",
  },
  "search.loadingDetails": "جارٍ تحميل التفاصيل…",
  "search.useEntry": "استخدام هذا العنصر",
  "search.backToResults": "العودة إلى النتائج",
  "search.results": "نتائج البحث",
  "search.additionalDetails": "تفاصيل إضافية غير متاحة",
  "search.rawgAttribution": "بيانات الألعاب مقدّمة من",
  "errors.entrySave": "تعذّر الحفظ. جرّب ملف صورة محليًا.",

  "common.cancel": "إلغاء",
  "common.savedFor": "تم الحفظ لـ {name}",
  "navigation.home": "الرئيسية",
  "navigation.favorites": "المفضلة",
  "navigation.settings": "الإعدادات",
  "navigation.everiaHome": "صفحة Everia الرئيسية",
  "navigation.close": "إغلاق قائمة التنقل",
  "navigation.open": "فتح قائمة التنقل",
  "navigation.search": "ابحث في عالمك",
  "navigation.searchPlaceholder": "ابحث في عالمك...",
  "navigation.addItem": "إضافة عنصر",
  "categories.games": "الألعاب",
  "categories.movies": "الأفلام",
  "categories.tv": "المسلسلات",
  "categories.novels": "الروايات",
  "categories.manga": "المانغا",
  "categories.anime": "الأنمي",
  "categories.gamesDescription": "عوالم تستكشفها",
  "categories.moviesDescription": "قصص للشاشة الكبيرة",
  "categories.tvDescription": "حلقة تلو الأخرى",
  "categories.novelsDescription": "رواية · رواية خفيفة · رواية ويب",
  "categories.mangaDescription": "مانغا · مانهوا · مانهوا صينية",
  "categories.animeDescription": "عوالم تنبض بالحياة",
  "subtypes.novel": "رواية",
  "subtypes.lightNovel": "رواية خفيفة",
  "subtypes.webNovel": "رواية ويب",
  "subtypes.manga": "مانغا",
  "subtypes.manhwa": "مانهوا",
  "subtypes.manhua": "مانهوا صينية",
  "statuses.wantToPlay": "أخطط للعب",
  "statuses.playing": "ألعبها حاليًا",
  "statuses.played": "أنهيت اللعب",
  "statuses.wantToWatch": "أخطط للمشاهدة",
  "statuses.watching": "أشاهدها حاليًا",
  "statuses.watched": "شاهدتها",
  "statuses.completed": "مكتمل",
  "statuses.wantToRead": "أخطط للقراءة",
  "statuses.reading": "أقرأها حاليًا",
  "statuses.read": "قرأتها",
  "statuses.onHold": "متوقف مؤقتًا",
  "statuses.dropped": "متروك",
  "creators.developer": "المطوّر",
  "creators.director": "المخرج",
  "creators.creator": "المُنشئ",
  "creators.author": "المؤلف",
  "creators.studio": "الاستوديو",
  "contributors.cast": "طاقم التمثيل",
  "contributors.artist": "الرسّام",
  "home.tagline": "عالمك الخاص",
  "home.entryCount": {
    zero: "{count} عناصر",
    one: "{count} عنصر",
    two: "{count} عنصران",
    few: "{count} عناصر",
    many: "{count} عنصرًا",
    other: "{count} عنصر",
  },
  "home.footer": "«قصص وعوالم وتجارب تبقى معك.»",
  "library.collection": "المجموعة",
  "library.sortBy": "ترتيب حسب",
  "library.recentlyAdded": "أُضيف حديثًا",
  "library.title": "العنوان",
  "library.releaseDate": "تاريخ الإصدار",
  "library.rating": "التقييم",
  "library.view": "عرض المجموعة",
  "library.gridView": "عرض الشبكة",
  "library.listView": "عرض القائمة",
  "library.filterByStatus": "تصفية حسب الحالة",
  "library.all": "الكل",
  "library.unknownCreator": "المُنشئ غير معروف",
  "library.empty": "لا توجد عناصر هنا بعد",
  "library.emptyPrompt": "أضف عنصرًا يدويًا أو ابحث عنه عبر الإنترنت.",
  "library.noStatusMatches": "لا توجد عناصر تطابق هذه الحالة.",
  "library.addItem": "إضافة عنصر",
  "favorites.subtitle": "القصص والعوالم الأقرب إليك.",
  "favorites.empty": "لا توجد مفضلات بعد",
  "favorites.emptyPrompt": "أضف عنصرًا إلى المفضلة لتجده هنا.",
  "settings.language": "اللغة",
  "errors.unavailable": "{source} غير متاح حاليًا.",
  "errors.savedDataUnreadable":
    "تعذّر تحميل بعض البيانات المحفوظة. احتُفظ بها، لكن حُظر حفظها حتى إصلاحها.",
  "errors.themeSave": "تعذّر حفظ المظهر.",
  "errors.sortSave": "تعذّر حفظ ترتيب العناصر.",
  "errors.viewSave": "تعذّر حفظ طريقة العرض.",
  "errors.removeConfirm": "هل تريد حذف هذا العنصر؟ لا يمكن التراجع عن ذلك.",
  "errors.removeFailed": "تعذّر حذف العنصر.",
  "errors.changesSave":
    "تعذّر حفظ التغييرات. تحقّق من المساحة المتاحة وحاول مجددًا.",
  "accessibility.openEntry": "فتح {title}",
  "accessibility.coverOf": "غلاف {title}",
  "accessibility.notRated": "لم يُقيّم بعد",
  "accessibility.ratingOutOfTen": "{rating} من 10",
  "accessibility.rateOutOfTen": "تقييم {rating} من 10",
  "accessibility.clearRating": "مسح",
} satisfies CatalogShape;
