/** English defines the keys and message kinds for every locale. */
export const en = {
  "common.cancel": "Cancel",
  "common.savedFor": "Saved for {name}",
  "navigation.home": "Home",
  "navigation.favorites": "Favorites",
  "navigation.settings": "Settings",
  "navigation.everiaHome": "Everia home",
  "navigation.close": "Close navigation",
  "navigation.open": "Open navigation",
  "navigation.search": "Search your universe",
  "navigation.searchPlaceholder": "Search your universe...",
  "navigation.addItem": "Add item",
  "categories.games": "Games",
  "categories.movies": "Movies",
  "categories.tv": "TV Shows",
  "categories.novels": "Novels",
  "categories.manga": "Manga",
  "categories.anime": "Anime",
  "categories.gamesDescription": "Worlds you can explore",
  "categories.moviesDescription": "Stories for the big screen",
  "categories.tvDescription": "One episode at a time",
  "categories.novelsDescription": "Novel · Light Novel · Web Novel",
  "categories.mangaDescription": "Manga · Manhwa · Manhua",
  "categories.animeDescription": "Worlds in motion",
  "subtypes.novel": "Novel",
  "subtypes.lightNovel": "Light Novel",
  "subtypes.webNovel": "Web Novel",
  "subtypes.manga": "Manga",
  "subtypes.manhwa": "Manhwa",
  "subtypes.manhua": "Manhua",
  "statuses.wantToPlay": "Want to Play",
  "statuses.playing": "Playing",
  "statuses.played": "Played",
  "statuses.wantToWatch": "Want to Watch",
  "statuses.watching": "Watching",
  "statuses.watched": "Watched",
  "statuses.completed": "Completed",
  "statuses.wantToRead": "Want to Read",
  "statuses.reading": "Reading",
  "statuses.read": "Read",
  "statuses.onHold": "On Hold",
  "statuses.dropped": "Dropped",
  "creators.developer": "Developer",
  "creators.director": "Director",
  "creators.creator": "Creator",
  "creators.author": "Author",
  "creators.studio": "Studio",
  "contributors.cast": "Cast",
  "contributors.artist": "Artist",
  "home.tagline": "Your Personal Universe",
  "home.entryCount": { one: "{count} entry", other: "{count} entries" },
  "home.footer": "“Stories, worlds, and experiences that stay with you.”",
  "library.collection": "COLLECTION",
  "library.sortBy": "Sort by",
  "library.recentlyAdded": "Recently added",
  "library.title": "Title",
  "library.releaseDate": "Release date",
  "library.rating": "Rating",
  "library.view": "Library view",
  "library.gridView": "Grid view",
  "library.listView": "List view",
  "library.filterByStatus": "Filter by status",
  "library.all": "All",
  "library.unknownCreator": "Unknown creator",
  "library.empty": "No entries here yet",
  "library.emptyPrompt":
    "Add an entry manually or find one with online search.",
  "library.noStatusMatches": "No entries match this status.",
  "library.addItem": "Add an item",
  "favorites.subtitle": "The stories and worlds you love most.",
  "favorites.empty": "No favorites yet",
  "favorites.emptyPrompt": "Mark an entry as a favorite to find it here.",
  "settings.language": "Language",
  "errors.unavailable": "{source} is currently unavailable.",
  "errors.savedDataUnreadable":
    "Some saved data could not be loaded. It has been preserved; saving that data is disabled until repaired.",
  "errors.themeSave": "Theme could not be saved.",
  "errors.sortSave": "Sort preference could not be saved.",
  "errors.viewSave": "View preference could not be saved.",
  "errors.removeConfirm": "Remove this entry? This cannot be undone.",
  "errors.removeFailed": "Entry could not be removed.",
  "errors.changesSave":
    "Changes could not be saved. Check storage space and retry.",
  "accessibility.openEntry": "Open {title}",
  "accessibility.coverOf": "Cover of {title}",
  "accessibility.notRated": "Not rated",
  "accessibility.ratingOutOfTen": "{rating} out of 10",
  "accessibility.rateOutOfTen": "Rate {rating} out of 10",
  "accessibility.clearRating": "Clear",
} as const;

export type MessageKey = keyof typeof en;
export type PluralCategory = Intl.LDMLPluralRule;
export type PluralMessage = { other: string } & Partial<
  Record<PluralCategory, string>
>;
export type CatalogShape = {
  [K in MessageKey]: (typeof en)[K] extends string ? string : PluralMessage;
};

export const fr = {
  "common.cancel": "Annuler",
  "common.savedFor": "Enregistré pour {name}",
  "navigation.home": "Accueil",
  "navigation.favorites": "Favoris",
  "navigation.settings": "Paramètres",
  "navigation.everiaHome": "Accueil d’Everia",
  "navigation.close": "Fermer la navigation",
  "navigation.open": "Ouvrir la navigation",
  "navigation.search": "Rechercher dans votre univers",
  "navigation.searchPlaceholder": "Rechercher dans votre univers...",
  "navigation.addItem": "Ajouter",
  "categories.games": "Jeux",
  "categories.movies": "Films",
  "categories.tv": "Séries TV",
  "categories.novels": "Romans",
  "categories.manga": "Mangas",
  "categories.anime": "Animés",
  "categories.gamesDescription": "Des mondes à explorer",
  "categories.moviesDescription": "Des histoires pour le grand écran",
  "categories.tvDescription": "Un épisode à la fois",
  "categories.novelsDescription": "Roman · Light novel · Web novel",
  "categories.mangaDescription": "Manga · Manhwa · Manhua",
  "categories.animeDescription": "Des mondes en mouvement",
  "subtypes.novel": "Roman",
  "subtypes.lightNovel": "Light novel",
  "subtypes.webNovel": "Web novel",
  "subtypes.manga": "Manga",
  "subtypes.manhwa": "Manhwa",
  "subtypes.manhua": "Manhua",
  "statuses.wantToPlay": "À jouer",
  "statuses.playing": "En cours",
  "statuses.played": "Terminé",
  "statuses.wantToWatch": "À regarder",
  "statuses.watching": "En cours",
  "statuses.watched": "Vu",
  "statuses.completed": "Terminé",
  "statuses.wantToRead": "À lire",
  "statuses.reading": "En cours",
  "statuses.read": "Lu",
  "statuses.onHold": "En pause",
  "statuses.dropped": "Abandonné",
  "creators.developer": "Développeur",
  "creators.director": "Réalisateur",
  "creators.creator": "Créateur",
  "creators.author": "Auteur",
  "creators.studio": "Studio",
  "contributors.cast": "Distribution",
  "contributors.artist": "Artiste",
  "home.tagline": "Votre univers personnel",
  "home.entryCount": { one: "{count} entrée", other: "{count} entrées" },
  "home.footer":
    "« Des histoires, des mondes et des expériences qui restent avec vous. »",
  "library.collection": "COLLECTION",
  "library.sortBy": "Trier par",
  "library.recentlyAdded": "Ajouts récents",
  "library.title": "Titre",
  "library.releaseDate": "Date de sortie",
  "library.rating": "Note",
  "library.view": "Affichage de la collection",
  "library.gridView": "Vue en grille",
  "library.listView": "Vue en liste",
  "library.filterByStatus": "Filtrer par statut",
  "library.all": "Tout",
  "library.unknownCreator": "Créateur inconnu",
  "library.empty": "Aucune entrée pour le moment",
  "library.emptyPrompt":
    "Ajoutez une entrée manuellement ou trouvez-en une avec la recherche en ligne.",
  "library.noStatusMatches": "Aucune entrée ne correspond à ce statut.",
  "library.addItem": "Ajouter une entrée",
  "favorites.subtitle": "Les histoires et les mondes que vous aimez le plus.",
  "favorites.empty": "Aucun favori pour le moment",
  "favorites.emptyPrompt":
    "Ajoutez une entrée à vos favoris pour la retrouver ici.",
  "settings.language": "Langue",
  "errors.unavailable": "{source} est actuellement indisponible.",
  "errors.savedDataUnreadable":
    "Certaines données enregistrées n’ont pas pu être chargées. Elles ont été préservées ; leur enregistrement est désactivé jusqu’à leur réparation.",
  "errors.themeSave": "Impossible d’enregistrer le thème.",
  "errors.sortSave": "Impossible d’enregistrer le tri.",
  "errors.viewSave": "Impossible d’enregistrer l’affichage.",
  "errors.removeConfirm":
    "Supprimer cette entrée ? Cette action est irréversible.",
  "errors.removeFailed": "Impossible de supprimer l’entrée.",
  "errors.changesSave":
    "Impossible d’enregistrer les modifications. Vérifiez l’espace disponible et réessayez.",
  "accessibility.openEntry": "Ouvrir {title}",
  "accessibility.coverOf": "Couverture de {title}",
  "accessibility.notRated": "Pas encore noté",
  "accessibility.ratingOutOfTen": "{rating} sur 10",
  "accessibility.rateOutOfTen": "Noter {rating} sur 10",
  "accessibility.clearRating": "Effacer",
} satisfies CatalogShape;

export const ar = {
  "common.cancel": "إلغاء",
  "common.savedFor": "تم الحفظ لـ {name}",
  "navigation.home": "الرئيسية",
  "navigation.favorites": "المفضلة",
  "navigation.settings": "الإعدادات",
  "navigation.everiaHome": "صفحة Everia الرئيسية",
  "navigation.close": "إغلاق قائمة التنقل",
  "navigation.open": "فتح قائمة التنقل",
  "navigation.search": "ابحث في عالمك",
  "navigation.searchPlaceholder": "ابحث في عالمك...",
  "navigation.addItem": "إضافة عنصر",
  "categories.games": "الألعاب",
  "categories.movies": "الأفلام",
  "categories.tv": "المسلسلات",
  "categories.novels": "الروايات",
  "categories.manga": "المانغا",
  "categories.anime": "الأنمي",
  "categories.gamesDescription": "عوالم تستكشفها",
  "categories.moviesDescription": "قصص للشاشة الكبيرة",
  "categories.tvDescription": "حلقة تلو الأخرى",
  "categories.novelsDescription": "رواية · رواية خفيفة · رواية ويب",
  "categories.mangaDescription": "مانغا · مانهوا · مانهوا صينية",
  "categories.animeDescription": "عوالم تنبض بالحياة",
  "subtypes.novel": "رواية",
  "subtypes.lightNovel": "رواية خفيفة",
  "subtypes.webNovel": "رواية ويب",
  "subtypes.manga": "مانغا",
  "subtypes.manhwa": "مانهوا",
  "subtypes.manhua": "مانهوا صينية",
  "statuses.wantToPlay": "أخطط للعب",
  "statuses.playing": "ألعبها حاليًا",
  "statuses.played": "أنهيت اللعب",
  "statuses.wantToWatch": "أخطط للمشاهدة",
  "statuses.watching": "أشاهدها حاليًا",
  "statuses.watched": "شاهدتها",
  "statuses.completed": "مكتمل",
  "statuses.wantToRead": "أخطط للقراءة",
  "statuses.reading": "أقرأها حاليًا",
  "statuses.read": "قرأتها",
  "statuses.onHold": "متوقف مؤقتًا",
  "statuses.dropped": "متروك",
  "creators.developer": "المطوّر",
  "creators.director": "المخرج",
  "creators.creator": "المُنشئ",
  "creators.author": "المؤلف",
  "creators.studio": "الاستوديو",
  "contributors.cast": "طاقم التمثيل",
  "contributors.artist": "الرسّام",
  "home.tagline": "عالمك الخاص",
  "home.entryCount": {
    zero: "{count} عناصر",
    one: "{count} عنصر",
    two: "{count} عنصران",
    few: "{count} عناصر",
    many: "{count} عنصرًا",
    other: "{count} عنصر",
  },
  "home.footer": "«قصص وعوالم وتجارب تبقى معك.»",
  "library.collection": "المجموعة",
  "library.sortBy": "ترتيب حسب",
  "library.recentlyAdded": "أُضيف حديثًا",
  "library.title": "العنوان",
  "library.releaseDate": "تاريخ الإصدار",
  "library.rating": "التقييم",
  "library.view": "عرض المجموعة",
  "library.gridView": "عرض الشبكة",
  "library.listView": "عرض القائمة",
  "library.filterByStatus": "تصفية حسب الحالة",
  "library.all": "الكل",
  "library.unknownCreator": "المُنشئ غير معروف",
  "library.empty": "لا توجد عناصر هنا بعد",
  "library.emptyPrompt": "أضف عنصرًا يدويًا أو ابحث عنه عبر الإنترنت.",
  "library.noStatusMatches": "لا توجد عناصر تطابق هذه الحالة.",
  "library.addItem": "إضافة عنصر",
  "favorites.subtitle": "القصص والعوالم الأقرب إليك.",
  "favorites.empty": "لا توجد مفضلات بعد",
  "favorites.emptyPrompt": "أضف عنصرًا إلى المفضلة لتجده هنا.",
  "settings.language": "اللغة",
  "errors.unavailable": "{source} غير متاح حاليًا.",
  "errors.savedDataUnreadable":
    "تعذّر تحميل بعض البيانات المحفوظة. احتُفظ بها، لكن حُظر حفظها حتى إصلاحها.",
  "errors.themeSave": "تعذّر حفظ المظهر.",
  "errors.sortSave": "تعذّر حفظ ترتيب العناصر.",
  "errors.viewSave": "تعذّر حفظ طريقة العرض.",
  "errors.removeConfirm": "هل تريد حذف هذا العنصر؟ لا يمكن التراجع عن ذلك.",
  "errors.removeFailed": "تعذّر حذف العنصر.",
  "errors.changesSave":
    "تعذّر حفظ التغييرات. تحقّق من المساحة المتاحة وحاول مجددًا.",
  "accessibility.openEntry": "فتح {title}",
  "accessibility.coverOf": "غلاف {title}",
  "accessibility.notRated": "لم يُقيّم بعد",
  "accessibility.ratingOutOfTen": "{rating} من 10",
  "accessibility.rateOutOfTen": "تقييم {rating} من 10",
  "accessibility.clearRating": "مسح",
} satisfies CatalogShape;
